
export const FETCH_MENU_LIST = 'cms/user/FETCH_MENU_LIST'
export const FETCH_MENU_LIST_SUCCESS = 'cms/user/FETCH_MENU_LIST_SUCCESS'
export const FETCH_MENU_LIST_ERROR = 'cms/user/FETCH_MENU_LIST_ERROR'